#code_root: "/export/home/rhaecker/documents/VAE/vae_edflow"
dataset: ed_vae.DatasetTrain
validation_dataset: ed_vae.DatasetEval
model: ed_vae.Model
iterator: ed_vae.Iterator
batch_size: 5
num_epochs: 1

code_root: null
integrations:
  wandb:
    active: True
    #name: "edflow_ml"
    #project: "proj_edflow_ml"

latent_dim: 20
data_path: "/export/home/rhaecker/documents/VAE/data/vae_max_var"
image_resolution: 64
validation_split: 0.2
shuffle_dataset: True
random_seed: 42