# info for run
code_root: null
integrations:
  wandb:
    active: True
#CUDA_VISIBLE_DEVICES: "7"
explanation: "Test only for debugging."
debug_log_level: True

# Dataset info
datasets:
  train: data.dataset.DatasetTrain
  validation: data.dataset.DatasetEval
data_root: /export/home/rhaecker/documents/research-of-latent-representation/data/only_dir_light_some_camera_theta

request_parameters: False
request_pose: False
request_tri: False
validation_split: 0.1
shuffle_dataset: True
image_resolution: 64

# Iterator info
iterator: iterator.Iterator
model: model.vae.Model
batch_size: 10
num_epochs: 15


# Model info

activation_function: "ReLU"
loss_function: "L2"
track_loss: "L1"
learning_rate: 0.0001
weight_decay: 0.00001 
#log_freq: 2000

variational:
  sigma: False
  sigmoid_regulator:
    start_amplitude: 1.E-5
    start_step: 60000
    width: 500
    amplitude: 0.001

# Conv parameters
conv:
  amount_conv_blocks: 3
  kernel_size: 5
  stride: 1
  conv_channels:
    [3,32,32,64]
  #padding: 2

upsample: 'nearest'
#'linear', 'nearest', 'bicubic'

linear:
  latent_dim: 64
