# info for run
code_root: null
integrations:
  wandb:
    active: False
#CUDA_VISIBLE_DEVICES: "7"
#explanation: "VAE-vae_var_some_sky--3_conv_blocks_up_nearest_var_conv."

# Dataset info
dataset: dataset.DatasetTrain
validation_dataset: dataset.DatasetEval
data_path: /export/home/rhaecker/documents/Machine-Learning-on-individual-data/data/three_var_some_fix_camera
request_parameters: False
request_pose: False
request_tri: True
validation_split: 0.1
shuffle_dataset: True
image_resolution: 64

# Iterator info
iterator: iterator.Iterator
model: conv_ae.Model
batch_size: 10
num_epochs: 15


# Model info

activation_function: "ReLU"
loss_function: "L2"
track_loss: "L1"
learning_rate: 0.0001
weight_decay: 0.00001 
#log_freq: 2000

variational:
  sigma: False
  sigmoid_regulator:
    start_amplitude: 1.E-5
    start_step: 60000
    width: 500
    amplitude: 0.001

# Conv parameters
conv:
  amount_conv_blocks: 3
  kernel_size: 5
  stride: 1
  conv_channels:
    [3,32,32,64]
  #padding: 2

upsample: 'nearest'
#'linear', 'nearest', 'bicubic'

linear:
  latent_dim: 64
