# info for run
code_root: null
integrations:
  wandb:
    active: False
    project: "Debug!"

# Dataset info
datasets:
  train: data.dataset.DatasetTrain
  validation: data.dataset.DatasetEval
data_root: /export/home/rhaecker/documents/research-of-latent-representation/data/only_dir_light_some_camera_theta

filter:
  same_filter: False
  train:
    total_branches: null
    #scale: [1.6,2]
    #theta: [0,2]
    total_cuboids: 4
    #same_material: True
  validation:


request_parameters: False
request_pose: False
request_tri: False
validation_split: 0.1
shuffle_dataset: False
image_resolution: 64

# Meta Info
#explanation: "GAN with VAE var reconstruction weight."
debug_log_level: True
#CUDA_VISIBLE_DEVICES: 5

# Iterator info
iterator: iterator.iterator.Iterator
model: model.gan.GAN
batch_size: 10
num_epochs: 1
random_seed: 13831

optimization: #to implement
  latent_sample: True
  update: "both" # "one" "one_prob"
  factor_disc_lr: 2

losses:
  discriminator_loss: "BCE" # "L2" "BCE"
  reconstruction_loss: "L2"
  reconstruction_loss_weight: 100
  #view_loss: "L1"
  KLD_loss:
    start_step: 20000
    width: 700
    amplitude: 0.0001

# Generator
learning_rate: 0.0001
beta1: 0.5
weight_decay: 0.000001 
#log_freq: 2000
activation_function: "ReLU"

variational:
  sigma: True

batch_norm: True
# Conv parameters
conv:
  n_channel_start: 32
  n_channel_max: 128
  first_layer: True
  final_layer: True