# info for run
code_root: null
integrations:
  wandb:
    active: False
    project: "Debug!"

# Dataset info
datasets:
  train: data.dataset.DatasetTrain
  validation: data.dataset.DatasetEval
data_root: /export/home/rhaecker/documents/research-of-latent-representation/data/only_dir_light_some_camera_theta

request_parameters: False
request_pose: False
request_tri: False
validation_split: 0.1
shuffle_dataset: True
image_resolution: 64

# Meta Info
#explanation: "GAN with VAE var reconstruction weight."
debug_log_level: True
CUDA_VISIBLE_DEVICES: 9

# Iterator info
iterator: iterator.iterator.Iterator
model: model.gan.GAN
batch_size: 10
num_epochs: 3

losses:
  reconstruction_loss: "L2"
  reconstruction_loss_weight: 20
  #view_loss: "L1"
  KLD_loss:
    start_step: 20000
    width: 700
    amplitude: 0.0001

# Generator
learning_rate: 0.0002
beta1: 0.5
weight_decay: 0.000001 
#log_freq: 2000
activation_function: "ReLU"

variational:
  sigma: True

batch_norm: True
# Conv parameters
conv:
  n_channel_start: 32
  n_channel_max: 256
  final_layer: True