# info for run
code_root: null
integrations:
  wandb:
    active: False
    project: "Debug!"

# Dataset info
datasets:
  train: data.dataset.DatasetTrain
  validation: data.dataset.DatasetEval
data_root: /export/home/rhaecker/documents/research-of-latent-representation/data/big_var_phi_theta

filter:
  same_filter: True
  local: True
  train:
    CameraRes_height: 512
    #total_branches: null
    #same_theta: True
    #same_scale: True
    #scale: 1.5
    #total_cuboids: 3
  #validation:
      #total_cuboids: 2

request_parameters: False

request_pose: False
request_tri: False
validation_split: 0.1
shuffle_dataset: True
shuffle_train: True
image_resolution: 64

# Meta Info
#explanation: "GAN with VAE var reconstruction weight."
debug_log_level: False
#CUDA_VISIBLE_DEVICES: 5

# Iterator info
iterator: iterator.iterator.Iterator
model: model.gan.GAN
batch_size: 32
#num_epochs: 1
num_steps: 10
#70000
random_seed: 13831

optimization: #to implement
  latent_sample: True
  update: "accuracy" # "one" "one_prob" "both" "accuracy"
  accuracy_threshold: 0.6
  factor_disc_lr: 2
  #reduce_lr: 0.5

losses:
  metric_loss:
    phi_margin: 15
    alpha_margin: 0.3
    weight: 50
  discriminator_loss: "BCE" # "L2" "BCE"
  reconstruction_loss: "L2"
  reconstruction_loss_weight: 500
  #view_loss: "L1"
  KLD_loss:
    start_step: 20000
    width: 700
    amplitude: 0.0001

# Generator
learning_rate: 0.0001
beta1: 0.5
weight_decay: 0.000001 
#log_freq: 2000
activation_function: "ReLU"

variational:
  sigma: True

batch_norm: True
# Conv parameters
conv:
  n_channel_start: 32
  n_channel_max: 128
  first_layer: True
  final_layer: True
  final_layer_kernel_size: 4