dataset: dataset.DatasetTrain
validation_dataset: dataset.DatasetEval
data_path: "/export/home/rhaecker/documents/Machine-Learning-on-individual-data/data/ae_only_phi"
validation_split: 0.1
shuffle_dataset: True
image_resolution: [64,64]


code_root: null
integrations:
  wandb:
    active: True
#    run_id: "test_run_id"

iterator: iterator.Iterator
model: conv_ae.Model
batch_size: 5
num_epochs: 100

explanation: "Only convolution test size of kernel and stride"

# Conv parameters
conv:
  amount_conv_blocks: 2
  kernel_size: 2
  stride: 2
  conv_channels:
    [3,32,64]
  #padding: 1
#linear:
#  bottleneck_size: 10

#upsample: 'nearest'
#'linear', 'bilinear', 'bicubic'

activation_function: "ReLU"
loss_function: "L2"
track_loss: "L1"
learning_rate: 0.0001
weight_decay: 0.00001 
log_freq: 2000