# info for run
code_root: null
integrations:
  wandb:
    active: False
#CUDA_VISIBLE_DEVICES: "7"
#explanation: "03.11 VAE whole only phi only conv."
explanation: "Test debug"
debug_log_level: True

# Dataset info
datasets:
  train: data.dataset.DatasetTrain
  validation: data.dataset.DatasetEval
data_root: /export/home/rhaecker/documents/research-of-latent-representation/data/ae_only_phi

request_parameters: False
request_pose: False
request_tri: False
validation_split: 0.1
shuffle_dataset: True
image_resolution: 64

# Iterator info
iterator: iterator.Iterator
model: model.vae.VAE_Model
batch_size: 10
num_epochs: 1


# Model info

activation_function: "ReLU"
loss_function: "L2"
track_loss: "L1"
learning_rate: 0.0001
weight_decay: 0.00001 
#log_freq: 2000

variational:
  sigma: False
  sigmoid_regulator:
    start_amplitude: 1.E-5
    start_step: 60000
    width: 500
    amplitude: 0.001
linear:
  latent_dim: 16

# Conv parameters
conv:
  n_blocks: 4
  kernel_size: 3
  stride: 2
  conv_channels:
    [3,32,32,64,64]
  #padding: 2

#upsample: 'nearest'
#'linear', 'nearest', 'bicubic'
