dataset: dataset.DatasetTrain
validation_dataset: dataset.DatasetEval
data_root: "/export/home/rhaecker/documents/Machine-Learning-on-individual-data/data/vae_var_some_sky"
validation_split: 0.1
shuffle_dataset: True
image_resolution: [64,64]

#CUDA_VISIBLE_DEVICES: "7"

code_root: null
integrations:
  wandb:
    active: True

iterator: iterator.Iterator
model: vae.Model
batch_size: 1
num_epochs: 50

activation_function: "ReLU"
loss_function: "L2"
track_loss: "L1"
learning_rate: 0.0001
weight_decay: 0.00001 
#log_freq: 2000

explanation: "VAE-vae_var_some_sky--only_4_conv_blocks."

variational:
  sigma: False
  sigmoid_regulator:
    start_amplitude: 1.E-5
    start_step: 50000
    width: 400
    amplitude: 0.001
# Conv parameters
conv:
  amount_conv_blocks: 4
  kernel_size: 2
  stride: 2
  conv_channels:
    [3,32,32,32,64]
  #padding: 2

#upsample: 'nearest'
#'linear', 'nearest', 'bicubic'

linear:
  latent_dim: 32
